# TODO ensure artefacts have limited lifetime on github packages
# TODO cancel current workflow if new run on the same branch, see https://stackoverflow.com/a/67939898
name: Build container image

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'conf/**'
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget
      - name: Install Apptainer
        run: |
          echo "Free space"
          df -h
          wget https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb
          sudo apt-get install -y ./apptainer_1.2.4_amd64.deb
      - uses: actions/checkout@v3
      - name: Build container
        working-directory: ./conf
        run: sudo apptainer build wrfmitgcm_env.sif wrfmitgcm_env.def 
      - name: Login and deploy
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          apptainer push conf/wrfmitgcm_env.sif oras://ghcr.io/${GITHUB_REPOSITORY}_wrfmitgcm_env:${tag}
